package com.mobisoft.taskmanagement.dto;

import java.time.OffsetDateTime;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.mobisoft.taskmanagement.entity.Project;
import com.mobisoft.taskmanagement.entity.User;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)

public class DepartmentDTO {

    private Long departmentId;
    @NotBlank(message = "Le nom du département ne peut pas être vide ou nul")
    private String departmentName;
    private String departmentSigle;
    private OffsetDateTime departmentCreatedAt;
    private OffsetDateTime departmentUpdatedAt;
    private Set<User> users;
    private Set<Project> projects;
    // Getters and setters (generated by Lombok)
}
